# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image_comparison_outputs.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eimage_comparison_outputs.proto\"!\n\x0eStatusResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"x\n\x15ImageComparisonOutput\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x10\n\x08\x64\x61tatype\x18\x04 \x01(\t\x12\r\n\x05shape\x18\x05 \x01(\x05\x12\x10\n\x08\x63ontents\x18\x06 \x03(\x0c\x32\x65\n\x1aInternalApiTemplateService\x12G\n\x1aInternalApiTemplateRequest\x12\x16.ImageComparisonOutput\x1a\x0f.StatusResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_comparison_outputs_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STATUSRESPONSE']._serialized_start=34
  _globals['_STATUSRESPONSE']._serialized_end=67
  _globals['_IMAGECOMPARISONOUTPUT']._serialized_start=69
  _globals['_IMAGECOMPARISONOUTPUT']._serialized_end=189
  _globals['_INTERNALAPITEMPLATESERVICE']._serialized_start=191
  _globals['_INTERNALAPITEMPLATESERVICE']._serialized_end=292
# @@protoc_insertion_point(module_scope)
